trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '33852162-1e66-4992-9ef8-8a909898f3ac'
  imageRepository: 'protikpatrainsuranceclaimsplatform'
  containerRegistry: 'protikinsuranceacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
